### ISSUE TITLE
Pagination: even two-digits numbers do not fit the dropdown 

### ISSUE THREAD

**Issue by nlopin** [freenowtech/wave#424] opened 2024-02-07 14:07 UTC
Even in [the docs](https://wave.free-now.com/?path=/docs/components-pagination--docs)

![CleanShot 2024-02-07 at 15 05 38@2x](https://github.com/freenowtech/wave/assets/1469636/22918f08-c01d-424c-b418-81448be38e46)

**Comment by martimalek** [comment] 2024-02-14 12:08
Closing this one since it's a duplicate of #331

**Closed by martimalek** 2024-02-14 12:08 UTC
Labels: bug
