### ISSUE TITLE
Make @freenow/wave compatible with React 17

### ISSUE THREAD

**Issue by snapsnapturtle** [freenowtech/wave#195] opened 2021-11-25 10:39 UTC
### Describe the feature you'd like
To be able to use wave with the new react versions, we will have to update the peer dependencies to also allow react@17. In addition we will have to check that the library is compatible with the changes in the new version of react.

### Describe alternatives you've considered
None, we should keep this compatible with react.

**Comment by martimalek** [comment] 2022-01-21 10:26
Hey folks, not sure what change was made but it seems to be working now with react 17

[CodeSandbox](https://codesandbox.io/s/wave-playground-react-17-zkkmz?file=/src/App.js)

**Comment by lloydaf** [comment] 2022-01-26 11:47
In that case I will close this issue, we can reopen this if we can reproduce a problem.

**Closed by lloydaf** 2022-01-26 11:47 UTC
Labels: enhancement
