### ISSUE TITLE
TextButton looks more like a button than text

### ISSUE THREAD

**Issue by chrisrolfe198** [freenowtech/wave#66] opened 2021-05-07 10:32 UTC
When using a text button within a table it does not line up because the TextButton has the same amount of padding as a Button as well as having the minimum width applied. (Note that the Actions title does not line up with the TextButton)

<img width="358" alt="Screenshot 2021-05-06 at 13 29 32" src="https://user-images.githubusercontent.com/2428612/117437092-0b6e4880-af30-11eb-92af-856ffb036832.png">

In the designs that I was provided for my feature this looks like this:
<img width="316" alt="Screenshot 2021-05-07 at 12 31 45" src="https://user-images.githubusercontent.com/2428612/117437216-335dac00-af30-11eb-858c-7561ecb43433.png">

**Comment by duranmla** [comment] 2021-05-07 10:35
@christopherrolfe198 thanks for letting us know this! it is very important to align how designers will express their design and the resources we give to devs to implement such things. **here seems like designers use a TexButton that doesn't have padding whereas the implementation differs** @agonzalezUX does it makes sense for us to remove the padding from `TextButton` or it is the design wrong?

**Comment by snapsnapturtle** [comment] 2021-05-07 10:40
That's a good point indeed. I think in some circumstances, like a cancel button in a modal, the padding makes a lot of sense. However providing an option to remove the padding for other use cases could be beneficial

**Comment by agonzalezUX** [comment] 2021-05-07 10:45
see image attached:
![image](https://user-images.githubusercontent.com/78148373/117438622-1629dd00-af32-11eb-9048-05b8ef0148f4.png)

**Comment by christopherrolfe198** [comment] 2021-05-07 10:54
@agonzalezUX - yeah this screenshot was taken whilst the feature was in development and has since been adjusted.

**Comment by agonzalezUX** [comment] 2021-05-07 10:56
then, I don't understand the issue, sorry 😅

**Comment by christopherrolfe198** [comment] 2021-05-07 11:03
So the issue is that the designs have an alignment with the table header, but the current components don't allow that:
![image](https://user-images.githubusercontent.com/2428612/117440617-96e9d880-af34-11eb-97f1-7f504de510af.png)
(See the lines to denote where the extra padding is)

**Comment by duranmla** [comment] 2021-05-07 11:05
@agonzalezUX that's a good thing we can take a look in a separate thread. Here the problem seems to be like this:
- Designers has an element of `TextButton` without padding and another `TextButton` with padding (for cases like @snapsnapturtle just mentioned)
- Developers only have a single `TextButton` with padding

Shall we enforce everyone to use a single version of the `TextButton` or shall we allow devs to have both versions?

**Comment by agonzalezUX** [comment] 2021-05-07 12:02
ahhhhhhmigo! the other alignement... In my opinion, flexibility is the leitmotiv of our system and I don't have any objection of adding it always that we document it properly :) so if you consider that including the option of having/not having padding is going to improve your work, fine for me

**Comment by duranmla** [comment] 2021-05-10 11:42
In that sense, I think the way to go is to add a prop to allow `TextButton` to not have paddings.

**Comment by rafael-sepeda** [comment] 2021-05-10 12:41
I agree with @agonzalezUX that if a designer wants to have a link -it is better to use a link, but not a button.
At least I would expect a button to have paddings, so in one row a textButton and a regular one will be in one line. But, maybe, we can make the left/right paddings optional.
Is that what you are proposing @duranmla ?

**Comment by duranmla** [comment] 2021-05-10 12:46
No @rafael-sepeda there are moments where the `TextButton` is needed because it is a button no a link.
Currently, it seems like:


> @agonzalezUX that's a good thing we can take a look in a separate thread. Here the problem seems to be like this:
> 
> * Designers has an element of `TextButton` without padding and another `TextButton` with padding (for cases like @snapsnapturtle just mentioned)
> * Developers only have a single `TextButton` with padding
> 
> Shall we enforce everyone to use a single version of the `TextButton` or shall we allow devs to have both versions?

In that sense, we either offer the two components for devs or we ensure everyone uses one _(but what it feels right is to allow padding or not padding variants)_

Worth to mention that the debate on button as a link I think is not that black and white. Take a look to this thread https://twitter.com/buildsghost/status/1389475246294532097?s=20

**Comment by nlopin** [comment] 2021-05-11 06:12
I see the "help wanted" tag, but as I see there is still a discussion. What solution do we need to apply? 

All buttons must have equal height so we can put them in a row.

**Comment by duranmla** [comment] 2021-05-11 15:44
There is no final decision here and also it seems everyone had a somewhat different definition of the problem despite my attempt to clarify at https://github.com/freenowtech/wave/issues/66#issuecomment-834272700 Let's go to the sync with this and made a decision there.

**Comment by duranmla** [comment] 2021-06-03 09:48
The conclusion for this thread so far:
- Add support for developers to remove horizontal padding on `<TextButton />`
- Aim for a future where TextButton doesn't have any padding by default _(not yet as it is breaking change **heavy**)_

**Comment by lloydaf** [comment] 2023-06-14 20:39
I will close this issue since there hasn't been activity in over 2 years, we can reopen this later if relevant.

**Closed by lloydaf** 2023-06-14 20:39 UTC
Labels: enhancement, conversation needed, design-review
